-- CreateTable
CREATE TABLE "users" (
    "id" SERIAL NOT NULL,
    "nome" TEXT,
    "naturalidade" TEXT,
    "estadocivil" TEXT,
    "datadenascimento" TEXT,
    "email" TEXT NOT NULL,
    "cpf" TEXT,
    "cep" TEXT,
    "senha" TEXT NOT NULL,
    "idade" TEXT,
    "telefone" TEXT,
    "apelido" TEXT,
    "NomeSocial" TEXT,
    "FiliacaoMae" TEXT,
    "FiliacaoPai" TEXT,
    "genero" TEXT,
    "OrientacaoSexual" TEXT,
    "Autodeclaracao" TEXT,
    "IdentidadeDeGenero" TEXT,
    "rg" TEXT,
    "SSP" TEXT,
    "UfOrgaoEmissor" TEXT,
    "Nacionalidade" TEXT,
    "UFdenaturalidade" TEXT,
    "Naturalidade" TEXT,
    "Profissao" TEXT,
    "Estado" TEXT,
    "municipo" TEXT,
    "endereco" TEXT,
    "bairro" TEXT,
    "numero" TEXT,
    "logradouro" TEXT,
    "complemento" TEXT,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bookmarks" (
    "id" SERIAL NOT NULL,
    "natureza" TEXT,
    "data_ocorrido" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "hora_ocorrido" TEXT,
    "cep_ocorrido" TEXT,
    "ufBO" TEXT,
    "municipioBO" TEXT,
    "logradouro" TEXT,
    "numero" INTEGER,
    "complemento" TEXT,
    "bairro" TEXT,
    "ponto_referencai" TEXT,
    "tipo_local" TEXT,
    "subgrupo" TEXT,
    "evento" TEXT,
    "pergunta_relativa" BOOLEAN,
    "descricao" TEXT,
    "nome" TEXT,
    "nascimento" TIMESTAMP(3),
    "cpf" TEXT,
    "envolvimento" TEXT,
    "email1" TEXT,
    "email2" TEXT,
    "telefone1" TEXT,
    "telefone2" TEXT,
    "telefone_fixo" TEXT,
    "rede_social1" TEXT,
    "rede_social2" TEXT,
    "rede_social3" TEXT,
    "apelido" TEXT,
    "nome_social" TEXT,
    "filiacao1" TEXT,
    "filiacao2" TEXT,
    "raca" TEXT,
    "sexo" TEXT,
    "orientacao" TEXT,
    "identidade_genero" TEXT,
    "autodeclaracao" TEXT,
    "rg" TEXT,
    "orgao_emissor" TEXT,
    "uf_orgao" TEXT,
    "nacionalidade" TEXT,
    "uf_naturalidade" TEXT,
    "profissao" TEXT,
    "cep" TEXT,
    "uf" TEXT,
    "municipio_Envolvido_Endereco" TEXT,
    "logradouro_Envolvido_Endereco" TEXT,
    "numero_Envolvido_Endereco" TEXT,
    "complemento_Envolvido_Endereco" TEXT,
    "bairro_Envolvido_Endereco" TEXT,
    "dono_envolvido" TEXT,
    "envolvimento_Objeto" TEXT,
    "descricao_objeto" TEXT,
    "classificao_objeto" TEXT,
    "numero_tel" TEXT,
    "operadora" TEXT,
    "marca_tel" TEXT,
    "modelo_tel" TEXT,
    "cor_tel" TEXT,
    "tipo_doc" TEXT,
    "num_doc" TEXT,
    "tipo_obj" TEXT,
    "descricao_obj" TEXT,
    "userId" INTEGER NOT NULL,

    CONSTRAINT "bookmarks_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "users_cpf_key" ON "users"("cpf");

-- AddForeignKey
ALTER TABLE "bookmarks" ADD CONSTRAINT "bookmarks_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
